CC = g++
CXXFLAGS = -stdlib=libc++ -std=c++20

all: task21 task23 task23p

task21: task21.o

task21.cpp:
	touch task21.cpp

task23: task23.o

task23.cpp:
	touch task23.cpp

clean:
	rm *.o task21 task22 task23